Flexible inventory
w3f/polkadot-secure-validator pull request #110
Opened 2020-12-17 19:16 UTC by remohammadi

Passing the path to inventory file as an argument to setup.sh makes it possible to maintain validators for different networks using only one local clone of polkadot-secure-validator repository. It will also be easier to maintain the inventory file outside the polkadot-secure-validator repo, probably in a separate git repo.

2021-01-14 21:22 UTC, lamafab requested changes
Thank you for the PR! Please checkout my proposed changes: https://github.com/remohammadi/polkadot-secure-validator/pull/1

2021-01-14 21:25 UTC, lamafab commented
@ironoa Would you mind merging https://github.com/remohammadi/polkadot-secure-validator/pull/1?

2021-01-16 18:20 UTC, remohammadi commented
Thank you for the changes. I merged them. But the pull request is not updated. 🤔  Shouldn't Github update the pull requests automatically when the branch is changed?

2021-01-16 22:07 UTC, lamafab approved these changes

2021-01-16 22:07 UTC, lamafab commented
@remohammadi made it took some time to have it displayed, but the commit is visible now. Thank! Will be merged, soon.

2021-01-20 20:50 UTC, merged